feat: add support for Arch Linux packages
goreleaser/nfpm pull request #543
Opened 2022-09-11 21:35 UTC by Arsen6331

This PR adds support for Arch Linux packages.

Like the previous PR (#141), this one generates `.PKGINFO`, `.INSTALL`, and `.MTREE` files.

Unlike that PR, this one compresses the package with a pure-Go Zstandard implementation, which conforms with the new standard for Arch packages.

I have successfully been able to install packages generated by this code, so it works, but there are no tests, so I am leaving it as a draft until I add tests to it.

Closes #133

2022-09-11 23:18 UTC, caarlos0 commented
amazing @Arsen6331! Let me know if you need any help!

2022-09-12 03:06 UTC, Arsen6331 commented
I've added the tests and comments, and fixed what the linter suggested.

2022-09-12 03:13 UTC, caarlos0 commented
Thanks, @Arsen6331 🚀 

could you make the changes to the docs as well? they live in the `www` folder.

2022-09-12 03:14 UTC, Arsen6331 commented
> could you make the changes to the docs as well? they live in the www folder.

Sure

2022-09-12 03:33 UTC, Arsen6331 commented
I've changed the docs

2022-09-13 00:25 UTC, djgilcrease requested changes

2022-09-13 00:25 UTC, djgilcrease commented on arch/arch.go
> +// validPkgName remoces any invalid characters from a string
```suggestion
// validPkgName removes any invalid characters from a string
```

2022-09-13 00:53 UTC, djgilcrease requested changes
- [x] Implement signed packages https://wiki.archlinux.org/title/DeveloperWiki:Package_signing Appears to create a `.sig` file to live outside the package?
- [ ] Implement `acceptance` tests

2022-09-13 00:55 UTC, Arsen6331 commented
> Implement signed packages [wiki.archlinux.org/title/DeveloperWiki:Package_signing](https://wiki.archlinux.org/title/DeveloperWiki:Package_signing) Appears to create a .sig file to live outside the package?

Yeah, it requires a separate file and I don't know how to implement that with the current API.

2022-09-13 05:48 UTC, djgilcrease commented
> 
> Yeah, it requires a separate file and I don't know how to implement that with the current API.

Just make a `doSign` method that writes the file alongside the package if the `info.ArchLinux.Signature.KeyFile` is not empty.

2022-09-13 05:50 UTC, Arsen6331 commented
> Just make a `doSign` method that writes the file alongside the package if the `info.ArchLinux.Signature.KeyFile` is not empty.

The issue with that is that the `Package()` method of the `Packager` interface I've implemented takes an `io.Writer` and writes to it. The packager doesn't actually control file creation.

2022-09-13 12:49 UTC, caarlos0 commented
> > Just make a `doSign` method that writes the file alongside the package if the `info.ArchLinux.Signature.KeyFile` is not empty.
> 
> The issue with that is that the `Package()` method of the `Packager` interface takes an `io.Writer` and writes to it. The packager doesn't actually control file creation.

ah yes, seems like one more thing we'll have to change... 

that said, maybe its for the best to actually break API compat for both this and #546?

2022-09-13 16:39 UTC, caarlos0 commented
> I am ok skipping signing for now so we can take a little time and design the build/sign API.

yeah, sounds good

2022-09-13 19:16 UTC, Arsen6331 commented
I've looked at the existing acceptance tests and I understand what they do, but I have no idea where to start in terms of implementing them for Arch. Can someone point me in the right direction?

2022-09-14 01:16 UTC, caarlos0 commented
@Arsen6331 If I'm not missing anything:

- add arch here: https://github.com/goreleaser/nfpm/blob/e6f966fa6f3d94c5fddb4decc14aa9294a4f6d8a/acceptance_test.go#L22
- create the dockerfiles and edit the goreleaser config files here: https://github.com/goreleaser/nfpm/tree/main/testdata/acceptance

you can start with the `min` and `simple` to get a handle on how it works... it is a bit complex - mainly because properly testing all this is complex, but once you get a hand of it it will hopefully make more sense...

2022-09-14 09:42 UTC, Arsen6331 commented
On Arch, packages cannot write to `/usr/sbin` as it is a symlink to `/usr/bin`, and pacman does not follow the symlink and therefore refuses to write to it. This is intentional behavior and not a bug in pacman. The `complex` acceptance test tries to add a file to `/usr/sbin`. How should I handle this? I could add an if statement in `TestCore()` that uses an Arch-specific file for the complex test. Would that be an acceptable solution?

2022-09-14 09:49 UTC, Arsen6331 commented
Oh, I just realized I could also do this if it's better:

```yaml
- src: ./testdata/fake
  dst: /usr/sbin/fake
  file_info:
    mode: 04755
  packager: deb
- src: ./testdata/fake
  dst: /usr/sbin/fake
  file_info:
    mode: 04755
  packager: rpm
- src: ./testdata/fake
  dst: /usr/sbin/fake
  file_info:
    mode: 04755
  packager: apk
- src: ./testdata/fake
  dst: /usr/bin/fake
  file_info:
    mode: 04755
  packager: archlinux
```

I think both solutions are a bit ugly, but I don't see any other solution.

2022-09-14 12:58 UTC, caarlos0 commented
I don't remember why we write to sbin to be honest, maybe someone else does? cc\ @goreleaser/nfpm 

if not, imho, we can change it to `/usr/bin`. 

if there's a reason, I would probably create a `complex` test config just for arch... probably...

2022-09-14 13:15 UTC, djgilcrease commented
I kind of like the complex config for the complex test as it shows what you may need to do

```yaml
- src: ./testdata/fake
  dst: /usr/sbin/fake
  file_info:
    mode: 04755
  packager: deb
- src: ./testdata/fake
  dst: /usr/sbin/fake
  file_info:
    mode: 04755
  packager: rpm
- src: ./testdata/fake
  dst: /usr/sbin/fake
  file_info:
    mode: 04755
  packager: apk
- src: ./testdata/fake
  dst: /usr/bin/fake
  file_info:
    mode: 04755
  packager: archlinux
```

2022-09-14 20:51 UTC, Arsen6331 commented
There is this multi-architecture image: [lopsided/archlinux](https://hub.docker.com/r/lopsided/archlinux/), which supports `amd64` and all the ARM variants, but it doesn't contain things like `grep`, which are used by the acceptance tests.

2022-09-14 21:02 UTC, Arsen6331 commented
There also seems to be a `devel` tag on that image, which has the `base-devel` group installed, so it has all the tools I need. That one should work, but then there's still no way to test `386`.

2022-09-15 00:43 UTC, caarlos0 commented
> I've implemented the acceptance tests. I added only `amd64` to `acceptance_test.go` for Arch because Arch only officially supports `x86_64`. This means that the official docker image only works on `amd64`. However, we should still support the unofficial architectures because they're used very often, especially the armv7 and arm64 ones. I don't know how to proceed with that.

I would say that, at least for now, we can go with the official support only...

2022-09-15 00:45 UTC, Arsen6331 commented
Ok, in that case, the acceptance tests are finished and pass. I did test them locally for both amd64 and the ARM variants, and they all pass there too.

2022-09-15 01:15 UTC, Arsen6331 commented
Should I add `archlinux` to the `pkgFormat` field in `.github/workflows/build.yml`?

2022-09-15 01:33 UTC, caarlos0 commented
> Should I add `archlinux` to the `pkgFormat` field in `.github/workflows/build.yml`?

yes, please!



> Ok, in that case, the acceptance tests are finished and pass. I did test them locally for both amd64 and the ARM variants, and they all pass there too.

awesome!

2022-09-15 01:36 UTC, Arsen6331 commented
Done

2022-09-15 13:25 UTC, djgilcrease approved these changes
LGTM

2022-09-17 01:59 UTC, Arsen6331 commented
I could also try to make a PR against https://github.com/goreleaser/goreleaser that integrates these changes and can be merged once they make it into a release.

2022-09-20 01:16 UTC, caarlos0 reviewed
on a first look it looks good to me! will see if I find some arch contributor to help review it as well! 

thanks again for the work on this! ❤️

2022-09-20 01:16 UTC, caarlos0 commented on apk/apk.go
> +	return ".deb"
should be apk here

2022-09-20 01:16 UTC, caarlos0 commented
> I could also try to make a PR against https://github.com/goreleaser/goreleaser that integrates these changes and can be merged once they make it into a release.

if you feel like it, go for it! If not, I can do it as well, no issues :)

2022-09-20 01:17 UTC, Arsen6331 commented on apk/apk.go
> +	return ".deb"
Oh, you're right, one second

2022-09-22 21:05 UTC, Arsen6331 commented
I went through a bunch of PKGBUILDs on the AUR to see if I missed anything and implemented all of it.

2022-10-13 20:35 UTC, caarlos0 commented
I'll review this again today and see that we have it merge soon! 🙏 Sorry for the delay, had a crazy couple of weeks :P

2022-10-13 20:56 UTC, Arsen6331 commented
> I'll review this again today and see that we have it merge soon! pray Sorry for the delay, had a crazy couple of weeks :P

No problem. Merge it whenever it's convenient for you, there's no rush.

2022-10-15 17:54 UTC, merged

2022-10-16 20:11 UTC, azat commented
Apparently right now archlinux packager does not support `type=config` for directories:

```
nfpm package --target .. --config clickhouse-server.yaml --packager archlinux
using archlinux packager...
read root/etc/clickhouse-server: is a directory
```

2022-10-17 11:59 UTC, caarlos0 commented
> Apparently right now archlinux packager does not support `type=config` for directories:
> 
> ```
> nfpm package --target .. --config clickhouse-server.yaml --packager archlinux
> using archlinux packager...
> read root/etc/clickhouse-server: is a directory
> ```

can you open an issue/PR?

2022-10-23 20:59 UTC, azat commented
>can you open an issue/PR?

#564